### ISSUE TITLE
Keyboard focus not taken from terminal apps

### ISSUE THREAD

**Issue by focusaurus** [FryJay/MenuHammer#10]
After months of everything working great, today I'm having a weird issue where I popup the menuhammer menu but keystrokes to select items are not processed and instead flow to the active application. This is only happening with 2 specific apps: kitty terminal and iterm2. If any other app is in focus with the menu on screen, the keystrokes are handled correctly. I thought maybe it was something weird with my specific terminal app but I've tried both kitty and iterm2 both in and out of a tmux session and they all prevent menuhammer from seeing the keystrokes somehow. Sorry to submit a tech support issue but I figured I'd see if anyone has seen this.

macos catalina 10.15.7

hammerspoon 0.9.93 (6148)

menuhammer commit 46ea97deca220bfae93fed461ff6841edd4a4d85

I tried the old update everything and reboot but still seeing the issue.

**Comment by focusaurus** [comment]
Weirdly I can reproduce the issue in Kitty and iTerm2 but not in Terminal.app. I'm very confused.

**Comment by focusaurus** [comment]
OK I think I figured it out. I must have accidentally hit ⌘+⇧+S in kitty which turns on secure input mode and seems to mask some keys from hammerspoon/menuhammer. Interestingly ESC comes through fine but not letters. Once I unchecked that, menuhammer works fine again. Sorry for the noise.

**Comment by FryJay** [comment]
Sorry for the delay replying but I'm glad you managed to work it out.
