### ISSUE TITLE
delay showing the menu 

### ISSUE THREAD

**Issue by dmgerman** [FryJay/MenuHammer#15]
Would you be open to a patch that delays showing the menu by a configurable delay?

The idea is that if the keys are done very quickly, then the menu is never shown. But if there is no input, the menu is shown after a given delay. I can submit a patch with this feature.

**Comment by FryJay** [comment]
My apologies on my delay responding, I haven't been working on this much lately. I'll take a look at your PR for this. Thanks for the contribution.

**Comment by FryJay** [comment]
Merged your PR for this.
