### ISSUE TITLE
Is there a way to send a return after typing text?

### ISSUE THREAD

**Issue by edmz** [FryJay/MenuHammer#5]
Thanks a lot for this awesome spoon, btw.

**Comment by edmz** [comment]
To be clear, I waould like to do (or something like that):

```
{cons.act.typetext, "whatever\n" }
```

**Comment by FryJay** [comment]
Does \n not work when you try it?  It should work as that is what I use for my personal config.  For example I have a lot of Finder configuration for opening folders like this:

```
{cons.cat.action, '', 'H', 'Hammerspoon', {
                 {cons.act.launcher, 'Finder'},
                 {cons.act.keycombo, {'cmd', 'shift'}, 'g'},
                 {cons.act.typetext, '~/.hammerspoon\n'},
}},
```

**Comment by edmz** [comment]
It doesn't work. At least not in google hangouts, where I'm using it to search for a contact.

**Comment by focusaurus** [comment]
@edmz try sending an ENTER keystroke either with `{cons.act.keycombo, {}, 'Return'}` or with a custom lua function that does `hs.eventtap.keyStroke({}, "Return")`.

**Comment by FryJay** [comment]
@focusaurus thanks for posting that fix.  It appears to work so I'm going to close this ticket for now and I'll reopen it if edmz reports that it doesn't work for them.
