### ISSUE TITLE
Execute action without closing menu?

### ISSUE THREAD

**Issue by NickSeagull** [FryJay/MenuHammer#8]
Hey, first of all, thanks a lot for putting the effort into creating this project. It is fantastic, and super useful for my workflow ❤️ 

I wanted to ask **if it is possible to execute an action without closing MenuHammer.** 

Here are different examples of use cases:

## Volume control menu

E.g., a menu that can be opened with `Option + Space -> V`, and then:

1. Allows increasing volume with `m`
2. Allows decreasing volume with `n`

This is important because if not, one would need to open it constantly with `Option + Space -> V`

## Window scaling/moving menus

E.g., some menus that can be opened with `Option + Space -> W -> S/M`, and then:

1. Scale/move left with `h`
2. Scale/move down with `j` 
3. Scale/move up with `k`
4. Scale/move right with `l` 

**These are just some examples** but I believe that a feature could be useful. Maybe it is possible already and I'm just not smart enough to figure it out 😅 

Anyways, thanks again!

**Comment by FryJay** [comment]
Hi Nick, I'm glad you like it.  Looks like I didn't document this but you can do this by adding "true" as a 6th argument to the menu action.

E.g. from my personal config:

```
            {cons.cat.action, '', 'K', "Volume Up 10%", {
                 {cons.act.mediakey, "adjustVolume", 10}},
             true,
            },
```

**Comment by NickSeagull** [comment]
Thanks! I've just opened a PR to document it :)
